### ISSUE TITLE
macos-latest unsupported architecture

### ISSUE THREAD

**Issue by antazoey** [gacts/install-geth-tools#67]
When using `macos-latest`, we are getting:

```
💾 Install Geth
...
  Error: Unsupported MacOS architecture
```

**Comment by tarampampam** [comment]
Could you please confirm release [v2.2.1](https://github.com/gacts/install-geth-tools/releases/tag/v1.2.2) solves this issue?

**Comment by antazoey** [comment]
> Could you please confirm release [v2.2.1](https://github.com/gacts/install-geth-tools/releases/tag/v1.2.2) solves this issue?

Yes, your latest release has resolved the issue, thank you.
(also it is 1.2.2 not 2.2.1 ◡̈ )
